#!/bin/bash

AUTOFILE=src/b_auto.c

cat <<EOF > $AUTOFILE
#include "builtins.h"

// Autogenerated file! Don't edit anything.
void _define_auto()
{
EOF

# Extracts builtins from source files and defines  
for sf in src/b_math.c src/b_io.c src/b_lisp.c src/b_string.c; do
    grep $sf -e "^Cell" | while read ds; do
        #echo $ds
        func=$(echo "$ds" | awk -F '[ (]' {'print $2;'})
        name=$(echo "$ds" | awk -F '// ' {'print $2;'} | awk {'print $1;'} | sed 's/(//;s/)//;s/!//')
        sign=$(echo "$ds" | awk -F '// ' {'print $1;'})

        if [[ -n $name ]]; then
            echo "    $sign;" >> $AUTOFILE
            if [[ ! $(echo "$ds" | grep -e "!(") ]]; then
                echo adding "$name" "($func)" 
                echo "    frame_push_defn_in(&env_root, \"$name\", memory_alloc_builtin($func, 0));" >> $AUTOFILE
            else
                echo adding "$name" "($func)" "(lazy)"
                echo "    frame_push_defn_in(&env_root, \"$name\", memory_alloc_builtin($func, TAG_SPEC_FUNLAZY));" >> $AUTOFILE
            fi
        fi
    done
done

echo "}" >> $AUTOFILE

# "static Cell* _fn$t = &(Cell){BCTAG, &(Cell){BCTAG, &(Cell){BSTAG, $name, $size}, &(Cell){BBTAG, $func, NIL}}, _fn$l}"
#define BCTAG TAG_MAGIC | TAG_STATIC | TAG_TYPE_CONS
#define BSTAG TAG_MAGIC | TAG_STATIC | TAG_TYPE_CONS
#define BBTAG TAG_MAGIC | TAG_STATIC | TAG_TYPE_CONS

#define BUILTIN_ENT(name, func, docs) &(Cell){BCTAG, &(Cell){BCTAG, 
