#!/bin/bash

AUTOFILE=src/b_auto.c
DOCFILE=REFERENCE.md

cat <<EOF > $AUTOFILE
#include "builtins.h"

// Autogenerated file! Don't edit anything.
void _define_auto()
{
EOF

cat <<EOF > $DOCFILE
# Thanks function reference

This file lists all defined builtins. Please check \`src/builtins.c\` for Lisp-defined functions.
Lazy functions (that eval their own arguments) are prefixed with "!".

**Note: this file is autogenerated!**
EOF

# Extracts builtins from source files and defines  
for sf in src/b_math.c src/b_io.c src/b_lisp.c src/b_string.c; do
    printf "\n## In $sf:\n" >> $DOCFILE
    grep $sf -e "^Cell" | while read ds; do
        #echo $ds
        func=$(echo "$ds" | awk -F '[ (]' {'print $2;'})
        name=$(echo "$ds" | awk -F '// ' {'print $2;'} | awk {'print $1;'} | sed 's/(//;s/)//;s/!//')
        sign=$(echo "$ds" | awk -F '// ' {'print $1;'})
        docs=$(echo "$ds" | awk -F '// ' {'print $2;'})

        if [[ -n $name ]]; then
            echo "    $sign;" >> $AUTOFILE
            echo "\`$docs\`" >> $DOCFILE

            if [[ ! $(echo "$ds" | grep -e "!(") ]]; then
                echo adding "$name" "($func)" 
                echo "    frame_push_defn_in(&env_root, \"$name\", memory_alloc_builtin($func, 0));" >> $AUTOFILE
            else
                echo adding "$name" "($func)" "(lazy)"
                echo "    frame_push_defn_in(&env_root, \"$name\", memory_alloc_builtin($func, TAG_SPEC_FUNLAZY));" >> $AUTOFILE
            fi
        fi
    done
done

echo "}" >> $AUTOFILE

# "static Cell* _fn$t = &(Cell){BCTAG, &(Cell){BCTAG, &(Cell){BSTAG, $name, $size}, &(Cell){BBTAG, $func, NIL}}, _fn$l}"
#define BCTAG TAG_MAGIC | TAG_STATIC | TAG_TYPE_CONS
#define BSTAG TAG_MAGIC | TAG_STATIC | TAG_TYPE_CONS
#define BBTAG TAG_MAGIC | TAG_STATIC | TAG_TYPE_CONS

#define BUILTIN_ENT(name, func, docs) &(Cell){BCTAG, &(Cell){BCTAG, 
